### ISSUE TITLE
create any stack operation program or any stack coding challenge 

### ISSUE THREAD

**Issue by prorammer** [prorammer/hactoberfest2021_pullrequest#1]
we have to create CPP program of stack operation or stack challenge.
please mention coding question in repo by just comment the question at the starting of your coding

EX:
if you have done a program of two stack in single array
then this question will be added in your repo at the starting of your PR just comment the question like given below
// C++ program  of two stack in single array

**Comment by WajihaFatim** [comment]
please assign this issue to me
